# Generated by Django 4.1.3 on 2022-11-27 14:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Sarlavha")),
                ("description", models.TextField(verbose_name="Malumot")),
            ],
            options={
                "verbose_name": "Biz Haqimizda",
                "verbose_name_plural": "Biz Haqimizda",
                "db_table": "about",
            },
        ),
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=255, verbose_name="Ismi")),
                (
                    "last_name",
                    models.CharField(max_length=255, verbose_name="Familiyasi"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Faqat Ozbekiston Raqami Bolish kerak",
                                regex="^998[0-9]{2}[0-9]{7}$",
                            )
                        ],
                        verbose_name="Nomeri",
                    ),
                ),
                ("message", models.TextField(verbose_name="Matni")),
            ],
            options={
                "verbose_name": "Kontaktdan",
                "verbose_name_plural": "Kontakdan",
                "db_table": "contact",
            },
        ),
        migrations.CreateModel(
            name="GalleryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Nomi")),
            ],
            options={
                "verbose_name": "Galeriya Kategoriyasi",
                "verbose_name_plural": "Galeriya Kategoriyasi",
                "db_table": "gal_category",
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="images/", verbose_name="Rasmi")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Nomi"
                    ),
                ),
                (
                    "little_desc",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Bafurcha Malumot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hamkorlar",
                "verbose_name_plural": "Hamkorlarimiz",
                "db_table": "partner",
            },
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Nomi")),
                ("start_date", models.DateField(verbose_name="Boshlangan Vaqti")),
                ("end_date", models.DateField(verbose_name="Tugagan Vaqti")),
                ("object", models.CharField(max_length=255, verbose_name="Manzil")),
                ("m2_quad", models.FloatField(verbose_name="M2")),
                (
                    "casting",
                    models.CharField(max_length=255, verbose_name="Kasting shakli"),
                ),
            ],
            options={
                "verbose_name": "Referenslar",
                "verbose_name_plural": "Referenslar",
                "db_table": "referenslar",
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="images/", verbose_name="Rasmi")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Nomi"
                    ),
                ),
                (
                    "little_desc",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Bafurcha Malumot",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kozyap_site.gallerycategory",
                        verbose_name="Kategoriyasi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Galleriya",
                "verbose_name_plural": "Galleriya",
                "db_table": "gallery",
            },
        ),
    ]
