# Generated by Django 4.1.3 on 2022-11-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kozyap_site", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Sarlavha")),
                ("description", models.TextField(verbose_name="Malumot")),
                ("image", models.ImageField(upload_to="images/", verbose_name="Rasm")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
