# Generated by Django 4.1.3 on 2022-11-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brigadier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Ism Familya')),
                ('tgid', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(max_length=20, null=True, verbose_name='Telegram Username')),
                ('phone', models.CharField(max_length=13, null=True)),
            ],
            options={
                'verbose_name': 'Brigadier',
                'verbose_name_plural': 'Brigadiers',
                'db_table': 'bridgadier',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56, verbose_name='Obyekt nomi')),
                ('location', models.CharField(max_length=56, verbose_name='Joylashuvi ')),
                ('geolokatsiyasi', models.CharField(max_length=512, verbose_name='Geolokatsiyasi')),
            ],
            options={
                'verbose_name': 'Obyekt',
                'verbose_name_plural': 'Obyektlar',
                'db_table': 'object',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=56, verbose_name='Ism Familya')),
                ('tgid', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(max_length=120, null=True, unique=True, verbose_name='Telegram Username')),
            ],
            options={
                'verbose_name': 'Ishchi',
                'verbose_name_plural': 'Ishchilar',
                'db_table': 'stuff',
            },
        ),
    ]
