# Generated by Django 4.1.3 on 2022-11-27 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brigadier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=50, verbose_name="Ism Familya"),
                ),
                (
                    "tgid",
                    models.BigIntegerField(unique=True, verbose_name="Telegram ID"),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=20, null=True, verbose_name="Telegram Username"
                    ),
                ),
                ("phone", models.CharField(max_length=13, null=True)),
            ],
            options={
                "verbose_name": "Brigader",
                "verbose_name_plural": "Brigadirlar",
                "db_table": "bridgadier",
            },
        ),
        migrations.CreateModel(
            name="Object",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=56, verbose_name="Obyekt nomi")),
                (
                    "location",
                    models.CharField(max_length=56, verbose_name="Joylashuvi "),
                ),
                (
                    "geolokatsiyasi",
                    models.CharField(max_length=129, verbose_name="Geolokatsiyasi"),
                ),
            ],
            options={
                "verbose_name": "Obyekt",
                "verbose_name_plural": "Obyektlar",
                "db_table": "object",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=56, verbose_name="Ism Familya"),
                ),
                (
                    "tgid",
                    models.IntegerField(
                        blank=True, null=True, unique=True, verbose_name="Telegram ID"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=120,
                        null=True,
                        unique=True,
                        verbose_name="Telegram Username",
                    ),
                ),
                (
                    "brigadier",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="staff",
                        to="kozyap.brigadier",
                        verbose_name="Brigadir",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ishchi",
                "verbose_name_plural": "Ishchilar",
                "db_table": "stuff",
            },
        ),
        migrations.CreateModel(
            name="ToDoList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Sana")),
                ("stuff_count", models.IntegerField(verbose_name="Hodimlar Soni")),
                ("todos", models.TextField(verbose_name="Qilingan Ishlar")),
                ("comment", models.TextField(null=True, verbose_name="Izoh")),
                (
                    "measure",
                    models.CharField(
                        max_length=56, null=True, verbose_name="O'lchov birligi"
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        max_length=128, null=True, verbose_name="Qilingan ish obyomi"
                    ),
                ),
                ("price", models.IntegerField(null=True, verbose_name="Narxi")),
                ("total", models.BigIntegerField(null=True, verbose_name="Jami")),
                (
                    "admin_comment",
                    models.TextField(null=True, verbose_name="Admin Izohi"),
                ),
                (
                    "brigadier",
                    models.ForeignKey(
                        default=-1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="kozyap.brigadier",
                        verbose_name="Brigadir",
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        default=-1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="kozyap.object",
                        verbose_name="Obyekt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qilinga Ish Qo'shish",
                "verbose_name_plural": "Qilingan Ishlar Ro'yhati",
                "db_table": "todos",
            },
        ),
        migrations.CreateModel(
            name="StaffReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Sana")),
                (
                    "work_hour",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="Ish Smena"
                    ),
                ),
                ("dwage", models.BigIntegerField(default=0)),
                (
                    "stuff",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="reports",
                        to="kozyap.staff",
                        verbose_name="Hodim",
                    ),
                ),
            ],
            options={
                "verbose_name": "KunlikHodim",
                "verbose_name_plural": "KunlikHodimlar",
                "db_table": "staff_report",
            },
        ),
        migrations.CreateModel(
            name="Intruments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=128, verbose_name="Holati")),
                (
                    "name",
                    models.CharField(max_length=128, verbose_name="Instrument Nomi"),
                ),
                (
                    "number",
                    models.CharField(
                        default=0, max_length=45, verbose_name="Instrument Nomeri"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        default=-1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="kozyap.brigadier",
                        verbose_name="Brigadier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uskuna",
                "verbose_name_plural": "Uskunalar",
                "db_table": "instrument",
            },
        ),
        migrations.CreateModel(
            name="ExChangeInstrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Olingan Sana")),
                (
                    "status",
                    models.CharField(
                        default="-", max_length=128, verbose_name="Instrument holati"
                    ),
                ),
                ("count", models.IntegerField(default=0, verbose_name="Soni")),
                (
                    "count_type",
                    models.CharField(
                        default="-", max_length=24, verbose_name="Sanoq Turi"
                    ),
                ),
                ("input", models.IntegerField(default=0, verbose_name="Kirim")),
                ("output", models.IntegerField(default=0, verbose_name="Chiqim")),
                (
                    "admin_comment",
                    models.CharField(
                        default="", max_length=128, verbose_name="Admin Izohi"
                    ),
                ),
                (
                    "given",
                    models.ForeignKey(
                        default=-1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="given",
                        to="kozyap.brigadier",
                        verbose_name="Kim Oldi",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        default=-1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="exchange",
                        to="kozyap.intruments",
                        verbose_name="Instrument",
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        default=-1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="kozyap.object",
                        verbose_name="Obyekt nomi",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        default=-1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="owner",
                        to="kozyap.brigadier",
                        verbose_name="Kim berdi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrument Oldi Berdi",
                "verbose_name_plural": "Instrument Ooldi Berdisi",
                "db_table": "exchangeinstrument",
            },
        ),
        migrations.CreateModel(
            name="Cost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "owner",
                    models.CharField(
                        max_length=128, null=True, verbose_name="Kim Berdi"
                    ),
                ),
                (
                    "stuff",
                    models.CharField(
                        max_length=128, null=True, verbose_name="Kim Oldi"
                    ),
                ),
                (
                    "reason",
                    models.CharField(max_length=128, null=True, verbose_name="Maqsadi"),
                ),
                ("input", models.IntegerField(null=True, verbose_name="Kirim")),
                ("output", models.IntegerField(null=True, verbose_name="Chiqim")),
                ("balance", models.IntegerField(verbose_name="Qolgan Summa")),
                (
                    "admin_comment",
                    models.TextField(null=True, verbose_name="Admin Izoh"),
                ),
                (
                    "object",
                    models.ForeignKey(
                        default=-1,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="costs",
                        to="kozyap.object",
                        verbose_name="Qaysi obyekt uchun harajat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pul Harajarti",
                "verbose_name_plural": "Pul Harajartlari",
                "db_table": "cost",
            },
        ),
    ]
