# Generated by Django 4.1.3 on 2022-11-27 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kozyap", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="object",
            name="brigadier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ojects",
                to="kozyap.brigadier",
                verbose_name="Brigadir",
            ),
        ),
    ]
