# Generated by Django 4.1.3 on 2022-11-24 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kozyap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brigadier',
            options={'verbose_name': 'Brigader', 'verbose_name_plural': 'Brigadirlar'},
        ),
        migrations.CreateModel(
            name='StaffReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('work_hour', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Ish Smena')),
                ('stuff_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='kozyap.staff', verbose_name='Hodim')),
            ],
        ),
    ]
