# Generated by Django 4.1.3 on 2022-11-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kozyap', '0002_alter_brigadier_options_staffreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffreport',
            options={'verbose_name': 'KunlikHodim', 'verbose_name_plural': 'KunlikHodimlar'},
        ),
        migrations.AlterModelTable(
            name='staffreport',
            table='staff_report',
        ),
    ]
