# Generated by Django 4.1.3 on 2022-11-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kozyap', '0003_alter_staffreport_options_alter_staffreport_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffreport',
            name='dwage',
            field=models.BigIntegerField(default=0),
        ),
    ]
