# Generated by Django 4.1.3 on 2022-11-24 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kozyap', '0004_staffreport_dwage'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='brigadier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='staff', to='kozyap.brigadier', verbose_name='Brigadir'),
        ),
        migrations.AlterField(
            model_name='staffreport',
            name='stuff_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='reports', to='kozyap.staff', verbose_name='Hodim'),
        ),
    ]
