# Generated by Django 4.1.3 on 2022-11-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kozyap', '0006_todolist_intruments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instrument',
            new_name='Intruments',
        ),
    ]
