# Generated by Django 4.1.3 on 2022-11-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kozyap', '0007_rename_instrument_intruments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='total',
            field=models.BigIntegerField(null=True, verbose_name='Jami'),
        ),
    ]
