# Generated by Django 4.1.3 on 2022-11-26 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kozyap', '0008_alter_todolist_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffreport',
            old_name='stuff_id',
            new_name='stuff',
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('owner', models.CharField(max_length=128, null=True, verbose_name='Kim Berdi')),
                ('stuff', models.CharField(max_length=128, null=True, verbose_name='Kim Oldi')),
                ('reason', models.CharField(max_length=128, null=True, verbose_name='Maqsadi')),
                ('input', models.IntegerField(null=True, verbose_name='Kirim')),
                ('output', models.IntegerField(null=True, verbose_name='Chiqim')),
                ('balance', models.IntegerField(verbose_name='Qolgan Summa')),
                ('admin_comment', models.TextField(null=True, verbose_name='Admin Izoh')),
                ('object', models.ForeignKey(default=-1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='kozyap.object', verbose_name='Qaysi obyekt uchun harajat')),
            ],
            options={
                'verbose_name': 'Pul Harajarti',
                'verbose_name_plural': 'Pul Harajartlari',
                'db_table': 'cost',
            },
        ),
    ]
