# Generated by Django 4.1.3 on 2022-11-26 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kozyap', '0009_rename_stuff_id_staffreport_stuff_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='intruments',
            name='number',
            field=models.CharField(default=0, max_length=45, verbose_name='Instrument Nomeri'),
        ),
        migrations.CreateModel(
            name='ExChangeInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Olingan Sana')),
                ('given', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='given', to='kozyap.brigadier', verbose_name='Kim Oldi')),
                ('instrument', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='exchange', to='kozyap.intruments', verbose_name='Instrument')),
                ('object', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='kozyap.object', verbose_name='Obyekt nomi')),
                ('owner', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='owner', to='kozyap.brigadier', verbose_name='Kim berdi')),
            ],
        ),
    ]
