# Generated by Django 4.1.3 on 2022-11-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kozyap', '0010_intruments_number_exchangeinstrument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangeinstrument',
            options={'verbose_name': 'Instrument Oldi Berdi', 'verbose_name_plural': 'Instrument Ooldi Berdisi'},
        ),
        migrations.AddField(
            model_name='exchangeinstrument',
            name='admin_comment',
            field=models.CharField(default='', max_length=128, verbose_name='Admin Izohi'),
        ),
        migrations.AddField(
            model_name='exchangeinstrument',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Soni'),
        ),
        migrations.AddField(
            model_name='exchangeinstrument',
            name='count_type',
            field=models.CharField(default='-', max_length=24, verbose_name='Sanoq Turi'),
        ),
        migrations.AddField(
            model_name='exchangeinstrument',
            name='input',
            field=models.IntegerField(default=0, verbose_name='Kirim'),
        ),
        migrations.AddField(
            model_name='exchangeinstrument',
            name='output',
            field=models.IntegerField(default=0, verbose_name='Chiqim'),
        ),
        migrations.AddField(
            model_name='exchangeinstrument',
            name='status',
            field=models.CharField(default='-', max_length=128, verbose_name='Instrument holati'),
        ),
        migrations.AlterField(
            model_name='object',
            name='geolokatsiyasi',
            field=models.CharField(max_length=129, verbose_name='Geolokatsiyasi'),
        ),
        migrations.AlterModelTable(
            name='exchangeinstrument',
            table='exchangeinstrument',
        ),
    ]
