# Generated by Django 4.1.3 on 2022-11-29 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kozyap', '0012_driver_transport_technictodos_driver_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='brigadier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ojects', to='kozyap.brigadier', verbose_name='Brigadir'),
        ),
    ]
