# Generated by Django 4.1.3 on 2022-11-29 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kozyap', '0013_object_brigadier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Intruments',
            new_name='Instrument',
        ),
    ]
